### ISSUE TITLE
Link to "5 Steps to Link your IaaS and PaaS Accounts " in What's new page is broken.

### ISSUE THREAD

**Issue by lionelmace** [IBM-Bluemix-Docs/whats-new#2]
@mekaufman The link to "5 Steps to Link your IaaS and PaaS Accounts " in What's new is broken.

- [x] Fix verified in [staging](https://console.stage1.bluemix.net/docs/overview/whats-new/index.html#whatsnew)
- [x] Fix verified in [master](https://console.bluemix.net/docs/overview/whats-new/index.html#whatsnew)

**Comment by mekaufman** [comment]
@leesakcp Can you fix the blog link that you added? It's not working.

**Comment by leesakcp** [comment]
Thanks, @lionelmace, for pointing this out.  This URL changed twice as we were going live and I didn't have the final one in there.  It's fixed now to be live in the next build so thanks VERY much for reporting it!  

I'll wait to verify in the build before I close the work item.

**Comment by leesakcp** [comment]
Fixed, verified, closing.  Thanks @lionelmace.
